[package]
name = "health-checker"
version = "0.1.0"
authors = ["Stefan Szasz <stefanszasz2@gmail.com>"]
edition = "2018"

[dependencies]
#hyper = "0.12"
#hyper-tls = "0.3.1"
reqwest = "0.9.11"
clap = "2.33.0"
log = "0.4"
simple_logger = "1.3.0"